### PR TITLE
Fix typo, numer -> number

### PR DESCRIPTION
**Pull request by kianmeng**
Found via `codespell -S po,.git`

### CODE REVIEW

**Comment by johannesjh** [comment]
hi, thank you for contributing to favagtk! 

btw, what is your experience with codespell? If it provides useful feedback (it probably does, thank you for finding the typo!) without too many false positives, then a corresponding pre-commit hook would make sense, what do you think? 

thx and best regards, Johannes

**Comment by johannesjh** [comment]
oh, and did you know that req2flatpak is actively being developed?
it is rather new, just a few weeks old, see 
https://github.com/johannesjh/req2flatpak

**Comment by kianmeng** [comment]
> btw, what is your experience with codespell? If it provides useful feedback (it probably does, thank you for finding the typo!) without too many false positives, then a corresponding pre-commit hook would make sense, what do you think?

It is good enough and actively maintained, see https://github.com/codespell-project/codespell. Furthermore, compares to other tools, the iterative mode (`-i`) definitely help in validating and checking process.

Adding a pre-commit hook should be rather straightforward. Let me know if you want me to create another PR?

**Comment by johannesjh** [comment]
that would be nice, yes please, thank you! 

btw, could you please use the gitlab repository over at https://gitlab.gnome.org/johannesjh/favagtk 

I am developing the project over there on gnome's gitlab... I am just mirroring the gitlab project to this github repo to improve visibility (my impression is that gnome's gitlab is poorly indexed by search engines).

**Pull request merged**
